---

- hosts: all
  name: Playbook to install docker on Ubuntu Servers

  tasks:

  - name: Install the latest version of packages
    become: true
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - python3-pip
      state: latest
      update_cache: yes

  - name: Add Docker GPG apt Key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: true
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

  - name: refresh apt cache
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400 # One day

  - name: Install Docker
    become: true
    apt:
      name:
       - docker-ce
      state: latest
 
  - name: Install docker python pip package
    become: true
    pip:
      name:
        - docker

  - name: Init a new swarm with default parameters
    become: true
    community.docker.docker_swarm:
      state: present
